const fs = require('fs');
const path = require('path');

// Logic copied from server.js to ensure files exist without running the server
const CONTENT_DIR = path.join(__dirname, 'content');
const LEVELS_DIR = path.join(CONTENT_DIR, 'levels');
const COURSES_DIR = path.join(CONTENT_DIR, 'courses');

function readJSON(filePath) {
    if (!fs.existsSync(filePath)) return null;
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

console.log('Building data files (CLI mode)...');

// 1. Read metadata
const metadata = readJSON(path.join(CONTENT_DIR, 'metadata.json')) || {};

// 2. Read Levels (Basic Info)
const levels = [];
if (fs.existsSync(LEVELS_DIR)) {
    fs.readdirSync(LEVELS_DIR).forEach(file => {
        if (file.endsWith('.json')) {
            const levelData = readJSON(path.join(LEVELS_DIR, file));
            levelData.courses = [];
            levels.push(levelData);
        }
    });
}

// 3. Generate data-core.js
const CORE_DATA = { ...metadata, levels: levels };
const coreContent = `// =====================================================
// data-core.js — Auto-generated by Content Builder
// =====================================================
const APP_DATA = ${JSON.stringify(CORE_DATA, null, 2)};
`;
fs.writeFileSync(path.join(__dirname, 'data-core.js'), coreContent);
console.log('✅ Generated data-core.js');

// 4. Generate data-{level}.js
levels.forEach(level => {
    const levelCourseDir = path.join(COURSES_DIR, level.id);
    const courses = [];

    if (fs.existsSync(levelCourseDir)) {
        fs.readdirSync(levelCourseDir).forEach(file => {
            if (file.endsWith('.json')) {
                const course = readJSON(path.join(levelCourseDir, file));
                courses.push(course);
            }
        });
    }

    const levelContent = `// =====================================================
// data-${level.id}.js — Auto-generated by Content Builder
// =====================================================
(function() {
    const level = APP_DATA.levels.find(l => l.id === "${level.id}");
    if (level) {
        level.courses = ${JSON.stringify(courses, null, 2)};
    }
})();
`;
    fs.writeFileSync(path.join(__dirname, `data-${level.id}.js`), levelContent);
    console.log(`✅ Generated data-${level.id}.js`);
});
