// =====================================================
// data-core.js — Auto-generated by Content Builder
// =====================================================
const APP_DATA = {
  "app": {
    "title": {
      "fr": "Physique Interactive",
      "ar": "الفيزياء التفاعلية"
    },
    "subtitle": {
      "fr": "Apprendre par la simulation",
      "ar": "التعلم عبر المحاكاة"
    },
    "welcome": {
      "fr": "Bienvenue ! Choisis ton niveau pour commencer.",
      "ar": "مرحبًا! اختر مستواك للبدء"
    },
    "footer": {
      "fr": "Application développée pour l'enseignement de la physique au collège — Maroc",
      "ar": "تطبيق مطوّر لتعليم الفيزياء بالإعدادي — المغرب"
    }
  },
  "ui": {
    "home": {
      "fr": "Accueil",
      "ar": "الرئيسية"
    },
    "courses": {
      "fr": "Cours",
      "ar": "الدروس"
    },
    "activities": {
      "fr": "Activités",
      "ar": "الأنشطة"
    },
    "back": {
      "fr": "Retour",
      "ar": "رجوع"
    },
    "next": {
      "fr": "Suivant",
      "ar": "التالي"
    },
    "previous": {
      "fr": "Précédent",
      "ar": "السابق"
    },
    "validate": {
      "fr": "Valider mes hypothèses",
      "ar": "تأكيد فرضياتي"
    },
    "startSimulation": {
      "fr": "Lancer la simulation",
      "ar": "ابدأ المحاكاة"
    },
    "fullscreen": {
      "fr": "Plein écran",
      "ar": "شاشة كاملة"
    },
    "exitFullscreen": {
      "fr": "Quitter plein écran",
      "ar": "إنهاء الشاشة الكاملة"
    },
    "showExplanation": {
      "fr": "Voir l'explication",
      "ar": "عرض الشرح"
    },
    "backToCourses": {
      "fr": "Retour aux cours",
      "ar": "العودة للدروس"
    },
    "chooseLevel": {
      "fr": "Choisir un niveau",
      "ar": "اختر المستوى"
    },
    "selectAnswer": {
      "fr": "Sélectionne une réponse",
      "ar": "اختر إجابة"
    },
    "yourPrediction": {
      "fr": "Ta prédiction",
      "ar": "توقعك"
    },
    "correctAnswer": {
      "fr": "Bonne réponse",
      "ar": "الإجابة الصحيحة"
    },
    "stepPrediction": {
      "fr": "Prédiction",
      "ar": "التوقع"
    },
    "stepObservation": {
      "fr": "Observation",
      "ar": "الملاحظة"
    },
    "stepExplanation": {
      "fr": "Explication",
      "ar": "الشرح"
    },
    "noCourses": {
      "fr": "Cours en cours de préparation…",
      "ar": "الدروس قيد التحضير…"
    },
    "writeAnswer": {
      "fr": "Écris ta réponse ici…",
      "ar": "…اكتب إجابتك هنا"
    },
    "installApp": {
      "fr": "Installer l'application",
      "ar": "تثبيت التطبيق"
    },
    "language": {
      "fr": "العربية",
      "ar": "Français"
    },
    "questionOf": {
      "fr": "Question {current} / {total}",
      "ar": "السؤال {current} / {total}"
    },
    "nextQuestion": {
      "fr": "Question suivante",
      "ar": "السؤال التالي"
    },
    "previousQuestion": {
      "fr": "Question précédente",
      "ar": "السؤال السابق"
    },
    "validatePredictions": {
      "fr": "Valider toutes mes prédictions",
      "ar": "تأكيد جميع توقعاتي"
    },
    "stepQuiz": {
      "fr": "Quiz",
      "ar": "اختبار"
    },
    "submitQuiz": {
      "fr": "Voir mon score",
      "ar": "عرض نتيجتي"
    },
    "quizScore": {
      "fr": "Ton score : {score} / {total}",
      "ar": "نتيجتك: {score} / {total}"
    },
    "quizPerfect": {
      "fr": "🎉 Parfait ! Tu as tout compris !",
      "ar": "🎉 ممتاز! فهمت كل شيء!"
    },
    "quizGood": {
      "fr": "👍 Bien joué ! Continue comme ça.",
      "ar": "👍 أحسنت! واصل هكذا."
    },
    "quizRetry": {
      "fr": "🔄 Relis l'explication et réessaie.",
      "ar": "🔄 أعد قراءة الشرح وحاول مرة أخرى."
    },
    "retryQuiz": {
      "fr": "Réessayer le quiz",
      "ar": "إعادة الاختبار"
    },
    "continueToQuiz": {
      "fr": "Tester ta compréhension",
      "ar": "اختبر فهمك"
    }
  },
  "levels": [
    {
      "id": "1ac",
      "name": {
        "fr": "1ère Année Collège",
        "ar": "السنة الأولى إعدادي"
      },
      "shortName": {
        "fr": "1AC",
        "ar": "1إع"
      },
      "icon": "🔬",
      "color": "#4CAF50",
      "gradient": "linear-gradient(135deg, #43A047, #66BB6A)",
      "courses": []
    },
    {
      "id": "2ac",
      "name": {
        "fr": "2ème Année Collège",
        "ar": "السنة الثانية إعدادي"
      },
      "shortName": {
        "fr": "2AC",
        "ar": "2إع"
      },
      "icon": "⚡",
      "color": "#2196F3",
      "gradient": "linear-gradient(135deg, #1E88E5, #42A5F5)",
      "courses": []
    },
    {
      "id": "3ac",
      "name": {
        "fr": "3ème Année Collège",
        "ar": "السنة الثالثة إعدادي"
      },
      "shortName": {
        "fr": "3AC",
        "ar": "3إع"
      },
      "icon": "🧲",
      "color": "#FF9800",
      "gradient": "linear-gradient(135deg, #F57C00, #FFB74D)",
      "courses": []
    }
  ]
};
