// =====================================================
// data-3ac.js — Auto-generated by Content Builder
// =====================================================
(function() {
    const level = APP_DATA.levels.find(l => l.id === "3ac");
    if (level) {
        level.courses = [];
    }
})();
